//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CitcWeb.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnnualCourse
    {
        public int Sn { get; set; }
        public int CourseSn { get; set; }
        public int ClassSn { get; set; }
        public int TotalHour { get; set; }
    
        public virtual ClassInfo ClassInfo { get; set; }
        public virtual Course Course { get; set; }
    }
}
