//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CitcWeb.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class BorrowHistory
    {
        public int Sn { get; set; }
        public int BookInfoSn { get; set; }
        public int ClassInfoSn { get; set; }
        public string StudentName { get; set; }
        public System.DateTime BorrowTime { get; set; }
        public Nullable<System.DateTime> ReturnTime { get; set; }
    
        public virtual BookInfo BookInfo { get; set; }
        public virtual ClassInfo ClassInfo { get; set; }
    }
}
