//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CitcWeb.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseSchedule
    {
        public int Sn { get; set; }
        public System.DateTime Date { get; set; }
        public int LessonStart { get; set; }
        public int LessonEnd { get; set; }
        public string Location { get; set; }
        public int ClassSn { get; set; }
        public Nullable<int> CourseSn { get; set; }
        public Nullable<int> TeacherSn { get; set; }
        public string OtherEvent { get; set; }
    
        public virtual ClassInfo ClassInfo { get; set; }
        public virtual Course Course { get; set; }
        public virtual Teacher Teacher { get; set; }
    }
}
