//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CitcWeb.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentReport
    {
        public int Sn { get; set; }
        public string StudentName { get; set; }
        public string StudentNo { get; set; }
        public string ReportTitle { get; set; }
        public System.DateTime UpdateTime { get; set; }
        public int ClassId { get; set; }
        public string PdfPath { get; set; }
        public string PptPath { get; set; }
        public int ClassSn { get; set; }
    
        public virtual ClassInfo ClassInfo { get; set; }
    }
}
