//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CitcWeb.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teacher
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Teacher()
        {
            this.CourseSchedule = new HashSet<CourseSchedule>();
        }
    
        public int Sn { get; set; }
        public string IdNum { get; set; }
        public string Name { get; set; }
        public string County { get; set; }
        public string PhoneNum { get; set; }
        public string MilNum { get; set; }
        public string Email { get; set; }
        public string PayBureauNum { get; set; }
        public string PayAccount { get; set; }
        public bool IsValid { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CourseSchedule> CourseSchedule { get; set; }
    }
}
